applications:
  python-app:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/LiorAtari/devops-project.git
      targetRevision: main
      path: python-chart
    destination:
      server: https://kubernetes.default.svc
      namespace: python-app
    syncPolicy:
      automated:
        prune: true
        selfHeal: true