# Add the devops-project repository
configs:
  repositories:
    git-repo:
      url: git@github.com:LiorAtari/devops-project.git
      type: git
      name: devops-project
      sshPrivateKeySecret:
        name: git-ssh
        key: sshPrivateKey