replicaCount: 1
image:
  repository: lioratari/develeap-python-app
  pullPolicy: Always
  tag: "latest"

env:
  DB_HOST: mysql.python-app.svc.cluster.local
  BACKEND: http://mysql.python-app.svc.cluster.local
  DB_USER: lior
  DB_NAME: exampleDb

service:
  type: ClusterIP
  port: 8080